name: page-stream-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core runtime: node via conda-forge
  - nodejs>=18,<21
  # Build toolchain helpers (optional)
  - jq
  - bash
  - coreutils
  # For optional debugging utilities
  - wget
  - curl
  # Python (lightweight) in case you want to script helpers
  - python=3.11
  - pip
  # Provide ffmpeg for local dev streaming without Docker
  - ffmpeg>=6
  # Provide X virtual framebuffer & related X11 libs (linux only). These are meta; may be no-ops on macOS.
  # Note: X11 packages removed for cross-platform compatibility; install manually if needed on Linux.
  # - xorg-libx11  # ensures X11 client libs present
  # - xorg-xauth
  # - xorg-xvfb-run
  # Node package install done via npm after env create
