export { default as streamsRouter } from './streams.js';
export { default as authRouter } from './auth.js';
export { default as auditRouter } from './audit.js';
export { default as templatesRouter } from './templates.js';
export { default as compositorsRouter } from './compositors.js';
export { default as groupsRouter } from './groups.js';
export { default as schedulesRouter } from './schedules.js';
export { default as alertsRouter } from './alerts.js';
export { default as metricsRouter } from '../metrics/index.js';
